name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # Extract version from setup.py
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(python setup.py --version)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      # Create Git tag
      - name: Create and push Git tag
        if: ${{ github.ref_name == 'main' }}
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v$PACKAGE_VERSION" -m "Release version $PACKAGE_VERSION"
          git push origin "v$PACKAGE_VERSION"

      # Build the package
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      # Publish to PyPI
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
